overrides:
  deepmerge-ts: '>=8.0.0'
  fastify: ^5.11.3
  ws@>=8.0.0 <8.21.0: ^8.21.3
  find-my-way@<9.6.1: ^9.7.0
  js-yaml@>=5.0.0 <=5.2.1: ^5.2.3

allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@sentry/node-cpu-profiler': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
