import 'dotenv/config';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'csv-parse/sync';
import { Prisma8Service } from '../prisma8/prisma8.service';
import { nowDb } from '../prisma8/timestamp';
import {
  CsvRow,
  parseCompanyRow,
  parseContactRow,
} from './tholemac-import.core';

const IMPORTS_DIR = join(process.cwd(), '..', 'imports files');
const MAP_DOC_PATH = join(
  process.cwd(),
  '..',
  'docs',
  'tholemac-import-legacy-id-map.md',
);

function readCsv(path: string): CsvRow[] {
  return parse(readFileSync(path, 'utf-8'), {
    columns: true,
    skip_empty_lines: true,
  });
}

function writeLegacyIdMapDoc(map: Map<number, number>): void {
  const rows = [...map.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([legacyId, clientId]) => `| ${legacyId} | ${clientId} |`)
    .join('\n');

  const content = `# Tholemac company.csv legacy id → Client.id map

Generated by \`src/scripts/import-tholemac.ts\` on ${new Date().toISOString()}.
Reference only — not stored in the database. Use this to resolve \`company_id\`
(or any other Tholemac export's FK into company.csv) onto the real \`Client.id\`.

| legacy id (company.csv \`id\`) | Client.id |
| --- | --- |
${rows}
`;

  writeFileSync(MAP_DOC_PATH, content);
}

async function main() {
  const db = new Prisma8Service();

  try {
    const firstUser = await db.orm.public.User.orderBy((u) =>
      u.id.asc(),
    ).first();
    if (!firstUser) {
      console.error(
        'no user found in database, cannot assign imported clients',
      );
      process.exit(1);
    }

    const companyRows = readCsv(join(IMPORTS_DIR, 'company.csv'));
    const legacyIdToClientId = new Map<number, number>();

    for (const row of companyRows) {
      const { legacyId, data } = parseCompanyRow(row);
      const client = await db.orm.public.Client.create({
        ...data,
        userId: firstUser.id,
        updatedAt: nowDb(),
      });
      legacyIdToClientId.set(legacyId, client.id);
    }
    console.log(`imported ${legacyIdToClientId.size} companies`);

    writeLegacyIdMapDoc(legacyIdToClientId);
    console.log(`wrote legacy id map to ${MAP_DOC_PATH}`);

    const contactRows = readCsv(join(IMPORTS_DIR, 'contact.csv'));
    let importedContacts = 0;

    for (const row of contactRows) {
      const { legacyCompanyId, data } = parseContactRow(row);
      const clientId = legacyIdToClientId.get(legacyCompanyId);
      if (clientId === undefined) {
        console.warn(
          `skipping contact row: no client found for legacy company id ${legacyCompanyId}`,
        );
        continue;
      }
      await db.orm.public.CompanyContact.create({
        ...data,
        clientId,
        updatedAt: nowDb(),
      });
      importedContacts++;
    }
    console.log(`imported ${importedContacts} contacts`);
  } finally {
    await db.onModuleDestroy();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
